A11y plugin was added
sbtsbol/eslint-config-sbtsbol pull request #3
Opened 2017-06-23 11:47 UTC by Creepypoke

Recommened rulesa for accessibility checks was added

2017-06-23 13:28 UTC, stcherenkov commented on rules/a11y.js
> +		'plugin:jsx-a11y/recommended'
Все правила по аксессабилити должны быть предупреждениями. Это сейчас так?

2017-06-24 06:40 UTC, elyashenko commented on rules/a11y.js
> +		'plugin:jsx-a11y/recommended'
судя по всему это не так. У разработчика плагина 2 конфига: recommended и strict. Но в обоих есть флаги error: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/src/index.js . Плагин юзать можно, но все правила надо перебивать на понижайку. А еще лучше расширить базовый конфиг и добавить свой блок warning. Тогда можно подключать любой конфиг на усмотрение разработчика. Допустим, в своей команде я захочу бОльшей строгости и заюзаю конфиг recommended.

2017-06-24 06:41 UTC, Creepypoke commented on rules/a11y.js
> +		'plugin:jsx-a11y/recommended'
Всё в процессе, не переживайте.

2017-06-24 20:04 UTC, stcherenkov commented on rules/a11y.js
> +		'plugin:jsx-a11y/recommended'
Можно оставить as is и выпустить мажорную версию.

2017-06-26 06:32 UTC, Creepypoke commented on rules/a11y.js
> +		'plugin:jsx-a11y/recommended'
Поменял всё на `warn`, чтобы не было так агрессивно)

Посмотрел в проектах новые правила. В принципе, там ничего убийственного нет. Нужно проверить репозиторий с компонентами

2017-06-26 06:50 UTC, stcherenkov requested changes

2017-06-26 06:50 UTC, stcherenkov commented on rules/a11y.js
> +                    'onClick',
У нас хэндлерсы начинаются с handle: handleClick, handleMouseDown etc.

2017-06-26 06:50 UTC, stcherenkov commented on rules/a11y.js
> +                    'onClick',
Аналогично, handleClick.

2017-06-26 08:49 UTC, Creepypoke commented on rules/a11y.js
> +                    'onClick',
... и я до сих пор не понимаю почему :)

2017-06-26 18:55 UTC, stcherenkov commented on rules/a11y.js
> +                    'onClick',
Такой нейминг конвеншн. Ну и ещё удобнее различать внешнее апи (из пропсов) и внутреннее.

2017-06-27 05:28 UTC, Creepypoke commented on rules/a11y.js
> +                    'onClick',
В любом случае, это про название событий, а не про имена методов.

2017-06-27 09:54 UTC, stcherenkov commented on rules/a11y.js
> +                    'onClick',
Тогда ок.

2017-06-27 09:54 UTC, stcherenkov approved these changes

2017-06-28 07:27 UTC, merged